[package]
name = "krondor"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version =  "2.0.10", features = ["rustls"] }
futures-util = "0.3.28"
reqwest = { version = "0.11.20", features = ["multipart", "stream", "json"] }
url = "2.4.1"
leptos = { version = "0.4.10", features = ["csr", "nightly"] }
serde_json = "1.0.107"
anyhow = "1.0.75"
leptos-struct-table = "0.3.2"
serde = "1.0.188"
async-trait = "0.1.73"
cid = "0.10.1"
leptos_router = { version = "0.4.10", features = ["csr", "nightly"] }
pulldown-cmark = "0.9.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32.0", features = ["macros", "full"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"