// This file is automatically generated by build.rs

pub const APP_VERSION: &'static str = "1.0.0";
pub const APP_NAME: &'static str = "krondor-rs";
pub const APP_POSTS_DIR: &'static str = "posts";
pub const APP_MANIFEST_FILE: &'static str = "manifest.json";
pub const APP_DIST_DIR: &'static str = "./.github/public";
