// This file is automatically generated by build.rs

#![allow(dead_code)]

pub const APP_VERSION: &str = "1.1.0";
pub const APP_NAME: &str = "krondor-rs";
pub const APP_ITEMS_DIR: &str = "items";
pub const APP_MANIFEST_FILE: &str = "manifest.json";
pub const APP_DIST_DIR: &str = "./.github/public";
