// This file is automatically generated by build.rs

pub const APP_VERSION: &str = "1.0.0";
pub const APP_NAME: &str = "krondor-rs";
pub const APP_POSTS_DIR: &str = "posts";
pub const APP_MANIFEST_FILE: &str = "manifest.json";
pub const APP_DIST_DIR: &str = "./.github/public";
